name: my_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1
  image_picker: ^1.2.0
  google_fonts: ^6.3.2
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  open_filex: ^4.5.0
  path_provider: ^2.1.3
  pdf: ^3.11.3
  printing: ^5.14.2
  supabase_flutter: ^1.3.0
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
